version: '3.4'
services:
  lb:
    image: nginx:1.21.6
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/loki.htpasswd:/etc/nginx/loki.htpasswd
      - ./config/mimir.htpasswd:/etc/nginx/mimir.htpasswd
    ports:
      - 3000:3000

  mimir:
    image: grafana/mimir:r185-de312f1
    restart: unless-stopped
    command: ["-config.file=/etc/mimir.yaml"]
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback.yaml:/etc/alertmanager-fallback.yaml
      - /etc/docker/data/mimir:/data

  loki:
    image: grafana/loki:2.3.0
    restart: unless-stopped
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./config/loki.yaml:/etc/loki/loki.yaml
      - /etc/docker/data/loki:/data

  minio:
    image: minio/minio:RELEASE.2022-05-08T23-50-31Z 
    restart: unless-stopped
    command: ["server", "--console-address=:3003", "/data"]
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_CONSOLE_SUBPATH=/minio/
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:3000/minio/
    volumes:
      - /etc/docker/data/minio:/data

  grafana:
    image: grafana/grafana:8.5.1-ubuntu
    restart: unless-stopped
    environment:
     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,yesoreyeram-boomtable-panel
    volumes:
      - /etc/docker/data/grafana/var-lib-grafana:/var/lib/grafana
      - /etc/docker/data/grafana/etc-grafana:/etc/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./resources/grafana-dashboards:/etc/grafana/provisioning/dashboards/dashboards
