apiVersion: 1
datasources:
  - uid: alertmanager
    name: Alertmanager
    type: alertmanager
    url: http://mimir:8080/mimir/
    access: proxy
  - name: Mimir
    type: prometheus
    access: proxy
    version: 1
    orgId: 1
    url: http://mimir:8080/mimir/prometheus
    editable: false
    isDefault: true
    jsonData:
      timeInterval: "5s"
      manageAlerts: true
      alertmanagerUid: alertmanager 
    secureJsonData:
  - name: Loki
    type: loki
    access: proxy
    version: 1
    orgId: 1
    url: http://loki:3002/loki/
    jsonData:
      manageAlerts: true
      alertmanagerUid: alertmanager
