apiVersion: 1
datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    version: 1
    orgId: 1
    url: http://mimir-lb:3003/prometheus
    editable: false
    isDefault: true
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
      timeInterval: "5s"
    secureJsonData:
      httpHeaderValue1: 'mimir'
