{
 "title": "System",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100-cpu_usage_idle{host=\"$hostname\", cpu=\"cpu-total\"}",
     "target": "asPercent(diffSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.mem.used'), fallbackSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_size'), constantLine(0))), seriesByTag('host=~${hostname:regex}', 'name=telegraf.mem.total')))"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(mem_used{host=\"$hostname\"}) - (arcstats_size{host=\"$hostname\"} OR vector(0))) / sum(mem_total{host=\"$hostname\"})",
     "target": "asPercent(diffSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.mem.used'), fallbackSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_size'), constantLine(0))), seriesByTag('host=~${hostname:regex}', 'name=telegraf.mem.total')))"
    }
   ]
  },
  {
   "title": "IO Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(diskio_io_time{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\"}[$__rate_interval])/10)",
     "target": "maxSeries(asPercent(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.io_time', '_name!=~zram*')), 1000))"
    }
   ]
  },
  {
   "title": "IO Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(diskio_read_time{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\"}[$__rate_interval]) / rate(diskio_reads{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\"}[$__rate_interval]))",
     "legendFormat": "reads",
     "target": "averageSeries(divideSeriesLists(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(read|write)_time', '_name!=~zram*')), perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(reads|writes)', '_name!=~zram*'))))"
    },
    {
     "expr": "max(rate(diskio_write_time{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\"}[$__rate_interval]) / rate(diskio_writes{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\"}[$__rate_interval]))",
     "legendFormat": "writes",
     "target": "averageSeries(divideSeriesLists(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(read|write)_time', '_name!=~zram*')), perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(reads|writes)', '_name!=~zram*'))))"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(diskio_read_bytes{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\"}[$__rate_interval]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(diskio_write_bytes{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\"}[$__rate_interval]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$hostname\", path=\"/\"}",
     "legendFormat": "root",
     "target": "seriesByTag('host=~${hostname:regex}', 'name=telegraf.disk.used_percent', 'fstype!=zfs', 'fstype!=nfs4')"
    },
    {
     "expr": "disk_used_percent{host=\"$hostname\", path=\"/\"}",
     "legendFormat": "zfs"
    }
   ]
  },
  {
   "title": "Inodes Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "max(disk_inodes_used{host=\"$hostname\", fstype!=\"zfs\", fstype!=\"nfs4\"} / disk_inodes_total{host=\"$hostname\", fstype!=\"zfs\", fstype!=\"nfs4\"})",
     "legendFormat": "root",
     "target": "seriesByTag('host=~${hostname:regex}', 'name=telegraf.disk.used_percent', 'fstype!=zfs', 'fstype!=nfs4')"
    }
   ]
  },
  {
   "title": "Znapzend - Snapshot Count",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "znapzend_count{host=\"$hostname\"} or vector(0)",
     "legendFormat": "{{dataset}}",
     "target": "aliasSub(aliasByTags(seriesByTag('host=~${hostname:regex}', 'name=telegraf.znapzend.count'), 'dataset'), '-', '/')"
    }
   ]
  },
  {
   "title": "Internet Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "internet_speed_download{host=\"$hostname\"}",
     "legendFormat": "down"
    },
    {
     "expr": "internet_speed_upload{host=\"$hostname\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Internet Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dns_query_query_time_ms{host=\"$hostname\"})",
     "legendFormat": "DNS"
    },
    {
     "expr": "internet_speed_latency{host=\"$hostname\"}",
     "legendFormat": "internet"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(net_bytes_recv{host=\"$hostname\", interface!=\"docker0\", interface!~\"veth.*\", interface!~\"br.*\"}[$__rate_interval]))",
     "legendFormat": "down"
    },
    {
     "expr": "sum(rate(net_bytes_sent{host=\"$hostname\", interface!=\"docker0\", interface!~\"veth.*\", interface!~\"br.*\"}[$__rate_interval]))",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(net_packets_recv{host=\"$hostname\", interface!=\"docker0\", interface!~\"veth.*\"}[$__rate_interval]))",
     "legendFormat": "down"
    },
    {
     "expr": "sum(rate(net_packets_sent{host=\"$hostname\", interface!=\"docker0\", interface!~\"veth.*\"}[$__rate_interval]))",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=\"$hostname\"}",
     "target": "seriesByTag('name=telegraf.system.uptime', 'host=~${hostname:regex}')"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_load5{host=\"$hostname\"}",
     "target": "seriesByTag('name=telegraf.system.load5', 'host=~${hostname:regex}')"
    }
   ]
  },
  {
   "title": "IO Wait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_iowait{host=\"$hostname\", cpu=\"cpu-total\"}",
     "target": "seriesByTag('host=~${hostname:regex}', 'name=telegraf.cpu.usage_iowait', 'cpu=cpu-total')"
    }
   ]
  },
  {
   "title": "ZFS ARC Hit Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(zfs_arcstats_hits{host=\"$hostname\"}[$__rate_interval]) / (rate(zfs_arcstats_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_misses{host=\"$hostname\"}[$__rate_interval]))",
     "target": "aliasSub(divideSeriesLists(aliasByTags(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_hits')), 'pools'), aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_(hits|misses)'), 'sum', 'pools')), 'pools')), \"divideSeries\\(([^,]*).*\", \"\\1 (ARC)\")"
    }
   ]
  },
  {
   "title": "Znapzend - Snapshot Age",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "znapzend_seconds_since_last{host=\"$hostname\"} or vector(0)",
     "legendFormat": "{{dataset}}",
     "target": "aliasSub(aliasByTags(seriesByTag('host=~${hostname:regex}', 'name=telegraf.znapzend.seconds_since_last'), 'dataset'), '-', '/')"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load5{host=\"$hostname\"}",
       "legendFormat": "{{__name__}}",
       "target": "aliasByNode(seriesByTag('name=~telegraf.system.load*', 'host=~${hostname:regex}'), 2)"
      }
     ]
    },
    {
     "title": "CPU Usage Per Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 7, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "{__name__=~\"cpu_usage.*\", host=\"$hostname\", cpu=\"cpu-total\", __name__!=\"cpu_usage_idle\"}",
       "legendFormat": "{{__name__}}",
       "target": "aliasByNode(seriesByTag('name=~telegraf.cpu.usage*', 'host=~${hostname:regex}', 'cpu=cpu-total', 'name!=telegraf.cpu.usage_idle'), 2)"
      }
     ]
    },
    {
     "title": "CPU Usage Per Core",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - cpu_usage_idle{host=\"$hostname\", cpu!=\"cpu-total\"}",
       "legendFormat": "{{cpu}}",
       "refCount": -1,
       "target": "aliasByTags(offset(scale(seriesByTag('name=telegraf.cpu.usage_idle', 'host=~${hostname:regex}', 'cpu!=cpu-total'), -1), 100), 'cpu')"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mem_used{host=\"$hostname\"}) - (arcstats_size{host=\"$hostname\"} OR vector(0))",
       "legendFormat": "real used",
       "target": "alias(diffSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.mem.used'), fallbackSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_size'), constantLine(0))), 'real used')"
      },
      {
       "expr": "sum({__name__=~\"mem.(cached|buffered|free)\", host=\"$hostname\"}) - (arcstats_size{host=\"$hostname\"} OR vector(0))",
       "legendFormat": "real free",
       "target": "alias(sum(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.mem.(cached|buffered|free)'), fallbackSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_size'), constantLine(0))), 'real free')"
      }
     ]
    },
    {
     "title": "Real Memory Usage (%)",
     "type": "timeseries",
     "description": "Excludes ARC",
     "gridPos": { "h": 8, "w": 9, "x": 7, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(mem_used{host=\"$hostname\"}) - (arcstats_size{host=\"$hostname\"} OR vector(0))) / sum(mem_total{host=\"$hostname\"})",
       "legendFormat": "real used (excluding ARC)",
       "target": "alias(asPercent(diffSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.mem.used'), fallbackSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_size'), constantLine(0))), seriesByTag('host=~${hostname:regex}', 'name=telegraf.mem.total')), 'real used (excluding ARC)')"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"mem.(cached|buffered|slab|free)\", host=\"$hostname\"}",
       "legendFormat": "{{__name__}}",
       "target": "aliasByNode(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.mem.(cached|buffered|slab|free)$'), 2)"
      },
      {
       "expr": "sum(mem_used{host=\"$hostname\"}) - (arcstats_size{host=\"$hostname\"} OR vector(0))",
       "legendFormat": "used",
       "target": "alias(diffSeries(seriesByTag('host=~${hostname:regex}', 'name=telegraf.mem.used'), fallbackSeries(sum(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_size')), constantLine(0))), 'used')"
      },
      {
       "expr": "arcstats_size{host=\"$hostname\"}",
       "legendFormat": "arc",
       "target": "alias(fallbackSeries(sum(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_size')), constantLine(0)), 'arc')"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"processes.*\", host=\"$hostname\"}, \"name\", \"$1\", \"__name__\", \"processes_(.*)\")",
       "legendFormat": "{{name}}",
       "target": "aliasByNode(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.processes.*', 'name!=~telegraf.processes.total*'), 2)"
      }
     ]
    },
    {
     "title": "Entropy Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 3, "x": 7, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kernel_entropy_avail",
       "legendFormat": "entropy",
       "target": "aliasByNode(perSecond(seriesByTag('host=~${hostname:regex}', 'name=telegraf.kernel.processes_forked')), 2)"
      }
     ]
    },
    {
     "title": "Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "label_replace(rate(interrupts_total[$__rate_interval]), \"device\", \"($1)\", \"device\", \"(.+)\")",
       "legendFormat": "[{{irq}}] {{type}} {{device}}"
      }
     ]
    },
    {
     "title": "Interrupts / CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(interrupts{host=\"$hostname\"}[$__rate_interval])) by (cpu)",
       "legendFormat": "CPU {{cpu}}"
      }
     ]
    },
    {
     "title": "Forks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kernel_processes_forked{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "forked",
       "target": "aliasByNode(perSecond(seriesByTag('host=~${hostname:regex}', 'name=telegraf.kernel.processes_forked')), 2)"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kernel_context_switches{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "switches",
       "target": "aliasByNode(perSecond(seriesByTag('host=~${hostname:regex}', 'name=telegraf.kernel.context_switches')), 2)"
      }
     ]
    },
    {
     "title": "Soft Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "label_replace(rate(soft_interrupts_total[$__rate_interval]), \"device\", \"($1)\", \"device\", \"(.+)\")",
       "legendFormat": "[{{irq}}]"
      }
     ]
    },
    {
     "title": "Soft Interrupts / CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(soft_interrupts{host=\"$hostname\"}[$__rate_interval])) by (cpu)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "disk_used_percent{host=\"$hostname\", fstype!=\"zfs\", fstype!=\"nfs4\"}",
       "legendFormat": "{{path}}",
       "target": "aliasSub(aliasSub(seriesByTag('host=~${hostname:regex}', 'name=telegraf.disk.used_percent', 'fstype!=zfs', 'fstype!=nfs4'), '-', '/'), '.*path=([^;]*).*', '\\1 - Used (%)')"
      }
     ]
    },
    {
     "title": "Inodes Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "disk_inodes_used{host=\"$hostname\", fstype!=\"zfs\", fstype!=\"nfs4\"} / disk_inodes_total{host=\"$hostname\", fstype!=\"zfs\", fstype!=\"nfs4\"}",
       "legendFormat": "{{path}}",
       "target": "aliasSub(aliasSub(seriesByTag('host=~${hostname:regex}', 'name=telegraf.disk.used_percent', 'fstype!=zfs', 'fstype!=nfs4'), '-', '/'), '.*path=([^;]*).*', '\\1 - Used (%)')"
      }
     ]
    },
    {
     "title": "ZFS - Disk Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "zpool_cap{host=\"$hostname\"}",
       "legendFormat": "{{name}}",
       "target": "aliasSub(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zpool.cap'), '.*_name=([^;]*).*', '\\1 - Used (%)')"
      }
     ]
    },
    {
     "title": "Znapzend - Snapshot Age",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "znapzend_seconds_since_last{host=\"$hostname\"}",
       "legendFormat": "{{dataset}}",
       "target": "aliasSub(aliasByTags(seriesByTag('host=~${hostname:regex}', 'name=telegraf.znapzend.seconds_since_last'), 'dataset'), '-', '/')"
      }
     ]
    },
    {
     "title": "Disk Free (GB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_free{host=\"$hostname\", fstype!=\"zfs\", fstype!=\"nfs4\"}",
       "legendFormat": "{{path}}",
       "target": "aliasSub(aliasSub(seriesByTag('host=~${hostname:regex}', 'name=telegraf.disk.used_percent', 'fstype!=zfs', 'fstype!=nfs4'), '-', '/'), '.*path=([^;]*).*', '\\1 - Used (%)')"
      }
     ]
    },
    {
     "title": "Inodes Free",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "disk_inodes_free{host=\"$hostname\", fstype!=\"zfs\", fstype!=\"nfs4\"}",
       "legendFormat": "{{path}}",
       "target": "aliasSub(aliasSub(seriesByTag('host=~${hostname:regex}', 'name=telegraf.disk.used_percent', 'fstype!=zfs', 'fstype!=nfs4'), '-', '/'), '.*path=([^;]*).*', '\\1 - Used (%)')"
      }
     ]
    },
    {
     "title": "ZFS - Disk Free (FB)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zpool_free{host=\"$hostname\"}",
       "legendFormat": "{{name}}",
       "target": "aliasSub(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zpool.cap'), '.*_name=([^;]*).*', '\\1 - Used (%)')"
      }
     ]
    },
    {
     "title": "Znapzend - Snapshot Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "znapzend_count{host=\"$hostname\"}",
       "legendFormat": "{{dataset}}",
       "target": "aliasSub(aliasByTags(seriesByTag('host=~${hostname:regex}', 'name=telegraf.znapzend.count'), 'dataset'), '-', '/')"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(diskio_read_bytes{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\", name=~\".*[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{name}} - reads",
       "target": "aliasSub(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(read|write)_bytes', '_name!=~zram*')), '.*(read|write)_bytes.*_name=([a-zA-Z0-9]*).*$', '\\2 (\\1)')"
      },
      {
       "expr": "rate(diskio_write_bytes{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\", name=~\".*[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{name}} - writes",
       "target": "aliasSub(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(read|write)_bytes', '_name!=~zram*')), '.*(read|write)_bytes.*_name=([a-zA-Z0-9]*).*$', '\\2 (\\1)')"
      }
     ]
    },
    {
     "title": "IOps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(diskio_read{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\", name=~\".*[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{name}} - reads",
       "target": "aliasSub(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(reads|writes)', '_name!=~zram*')), '.*(reads|writes);.*_name=([a-zA-Z0-9]*).*$', '\\2 (\\1)')"
      },
      {
       "expr": "rate(diskio_writes{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\", name=~\".*[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{name}} - writes",
       "target": "aliasSub(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(reads|writes)', '_name!=~zram*')), '.*(reads|writes);.*_name=([a-zA-Z0-9]*).*$', '\\2 (\\1)')"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(diskio_io_time{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\", name=~\"[^0-9]+\"}[$__rate_interval])/10",
       "legendFormat": "{{name}}",
       "target": "aliasSub(asPercent(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.io_time', '_name!=~zram*')), 1000), '.*_name=([a-zA-Z0-9]*).*$', '\\1')"
      }
     ]
    },
    {
     "title": "IO Queue (instant)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "Instant Value" }
     ],
     "targets": [
      {
       "expr": "diskio_iops_in_progress{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\", name=~\".*[0-9]+\"}",
       "legendFormat": "{{name}}",
       "target": "aliasByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.iops_in_progress', '_name!=~zram*'), '_name')"
      }
     ]
    },
    {
     "title": "IO Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(diskio_read_time{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\", name=~\".*[0-9]+\"}[$__rate_interval]) / rate(diskio_reads{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\"}[$__rate_interval])",
       "legendFormat": "{{name}} - reads",
       "target": "aliasSub(divideSeriesLists(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(read|write)_time', '_name!=~zram*')), perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(reads|writes)', '_name!=~zram*'))), \".*(read|write)_time;_name=([^;]*).*\", \"\\2 (\\1)\")"
      },
      {
       "expr": "rate(diskio_write_time{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\", name=~\".*[0-9]+\"}[$__rate_interval]) / rate(diskio_writes{host=\"$hostname\", _name!=\"zram\", name!~\"loop.*\"}[$__rate_interval])",
       "legendFormat": "{{name}} - writes",
       "target": "aliasSub(divideSeriesLists(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(read|write)_time', '_name!=~zram*')), perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.diskio.(reads|writes)', '_name!=~zram*'))), \".*(read|write)_time;_name=([^;]*).*\", \"\\2 (\\1)\")"
      }
     ]
    },
    {
     "title": "ZFS - ARC Hit % (Prefetch / Demand)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_prefetch_data_hits{host=\"$hostname\"}[$__rate_interval]) / (rate(zfs_arcstats_prefetch_data_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_prefetch_data_misses{host=\"$hostname\"}[$__rate_interval]))",
       "legendFormat": "{{pools}} (Prefetch Data)",
       "target": "aliasSub(divideSeriesLists(aliasByTags(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_prefetch_data_hits')), 'pools'), aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_prefetch_data_(hits|misses)'), 'sum', 'pools')), 'pools')), \"divideSeries\\(([^,]*).*\", \"\\1 (Prefetch Data)\")"
      },
      {
       "expr": "rate(zfs_arcstats_demand_metadata_hits{host=\"$hostname\"}[$__rate_interval]) / (rate(zfs_arcstats_demand_metadata_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_demand_metadata_misses{host=\"$hostname\"}[$__rate_interval]))",
       "legendFormat": "{{pools}} (Demand Metadata)",
       "target": "aliasSub(divideSeriesLists(aliasByTags(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_demand_metadata_hits')), 'pools'), aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_demand_metadata_(hits|misses)'), 'sum', 'pools')), 'pools')), \"divideSeries\\(([^,]*).*\", \"\\1 (Demand Metadata)\")"
      },
      {
       "expr": "rate(zfs_arcstats_demand_data_hits{host=\"$hostname\"}[$__rate_interval]) / (rate(zfs_arcstats_demand_data_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_demand_data_misses{host=\"$hostname\"}[$__rate_interval]))",
       "legendFormat": "{{pools}} (Demand data)",
       "target": "aliasSub(divideSeriesLists(aliasByTags(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_demand_data_hits')), 'pools'), aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_demand_data_(hits|misses)'), 'sum', 'pools')), 'pools')), \"divideSeries\\(([^,]*).*\", \"\\1 (Demand Data)\")"
      },
      {
       "expr": "rate(zfs_arcstats_prefetch_metadata_hits{host=\"$hostname\"}[$__rate_interval]) / (rate(zfs_arcstats_prefetch_metadata_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_prefetch_metadata_misses{host=\"$hostname\"}[$__rate_interval]))",
       "legendFormat": "{{pools}} (Prefetch metadata)",
       "target": "aliasSub(divideSeriesLists(aliasByTags(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_prefetch_metadata_hits')), 'pools'), aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_prefetch_metadata_(hits|misses)'), 'sum', 'pools')), 'pools')), \"divideSeries\\(([^,]*).*\", \"\\1 (Prefetch Metadata)\")"
      }
     ]
    },
    {
     "title": "ZFS - ARC Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zfs_arcstats_c{host=\"$hostname\"}",
       "legendFormat": "Target Size - MRU/MFU",
       "target": "alias(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_c'), 'Target Size - MRU/MFU')"
      },
      {
       "expr": "zfs_arcstats_c_max{host=\"$hostname\"}",
       "legendFormat": "Max Size - MRU/MFU",
       "target": "alias(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_c_max'), 'Max Size - MRU/MFU')"
      },
      {
       "expr": "zfs_arcstats_p{host=\"$hostname\"}",
       "legendFormat": "Current Size - Most Recently Used",
       "target": "alias(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_p'), 'Current Size - Most Recently Used')"
      },
      {
       "expr": "zfs_arcstats_mfu_size{host=\"$hostname\"}",
       "legendFormat": "Current Size - Most Frequently Used",
       "target": "alias(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_mfu_size'), 'Current Size - Most Frequently Used')"
      },
      {
       "expr": "zfs_arcstats_size",
       "legendFormat": "Current Size - All",
       "target": "alias(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_size'), 'Current Size - All')"
      }
     ]
    },
    {
     "title": "ZFS - ARC Hit % (incl. ghost hits)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_hits{host=\"$hostname\"}[$__rate_interval]) / (rate(zfs_arcstats_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_misses{host=\"$hostname\"}[$__rate_interval]))",
       "legendFormat": "{{pools}} (ARC)",
       "target": "aliasSub(divideSeriesLists(aliasByTags(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_hits')), 'pools'), aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_(hits|misses)'), 'sum', 'pools')), 'pools')), \"divideSeries\\(([^,]*).*\", \"\\1 (ARC)\")"
      },
      {
       "expr": "rate(zfs_arcstats_mru_hits{host=\"$hostname\"}[$__rate_interval]) / (rate(zfs_arcstats_mru_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_mru_misses{host=\"$hostname\"}[$__rate_interval]))",
       "legendFormat": "{{pools}} (MRU)",
       "target": "aliasSub(divideSeriesLists(aliasByTags(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_mru_hits')), 'pools'), aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_mru_(hits|misses)'), 'sum', 'pools')), 'pools')), \"divideSeries\\(([^,]*).*\", \"\\1 (MRU)\")"
      },
      {
       "expr": "rate(zfs_arcstats_mfu_hits{host=\"$hostname\"}[$__rate_interval]) / (rate(zfs_arcstats_mfu_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_mfu_misses{host=\"$hostname\"}[$__rate_interval]))",
       "legendFormat": "{{pools}} (MFU)",
       "target": "aliasSub(divideSeriesLists(aliasByTags(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_mfu_hits')), 'pools'), aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_mfu_(hits|misses)'), 'sum', 'pools')), 'pools')), \"divideSeries\\(([^,]*).*\", \"\\1 (MFU)\")"
      }
     ]
    },
    {
     "title": "ZFS - ARC Accesses / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_misses{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "{{pools}}",
       "target": "aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_(hits|misses)'), 'sum', 'pools')), 'pools')"
      }
     ]
    },
    {
     "title": "ZFS - ARC Metadata Size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zfs_arcstats_arc_meta_used{host=\"$hostname\"}",
       "legendFormat": "{{pools}} (used)",
       "target": "aliasByNode(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_arc_meta_(limit|used|max)'), 2)"
      },
      {
       "expr": "zfs_arcstats_arc_meta_limit{host=\"$hostname\"}",
       "legendFormat": "{{pools}} (limit)"
      },
      {
       "expr": "zfs_arcstats_arc_meta_max{host=\"$hostname\"}",
       "legendFormat": "{{pools}} (max)"
      }
     ]
    },
    {
     "title": "ZFS - ARC Hash Elements Capacity & Collions / sec",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "zfs_arcstats_hash_elements{host=\"$hostname\"} / zfs_arcstats_hash_elements_max{host=\"$hostname\"}",
       "legendFormat": "{{pools}} (Usage)",
       "target": "aliasSub(divideSeriesLists(aliasByTags(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_hash_elements'), 'pools'), aliasByTags(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_hash_elements_max'), 'pools')), \".*\\(([^,]*).*\", \"Elements (\\1)\")"
      },
      {
       "expr": "rate(zfs_arcstats_hash_collisions{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "{{pools}} (Collisions)",
       "target": "aliasSub(perSecond(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_hash_collisions')), '.*pools=([^;)]*).*', 'Collisions (\\1)')"
      }
     ]
    },
    {
     "title": "ZFS - ARC Hash Chains",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zfs_arcstats_hash_chains{host=\"$hostname\"}  ",
       "legendFormat": "{{pools}} (Chains)",
       "target": "aliasSub(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_hash_chains'), '.*pools=([^;]*).*', 'Chains (\\1)')"
      },
      {
       "expr": "zfs_arcstats_hash_chain_max{host=\"$hostname\"}",
       "legendFormat": "{{pools}} (Chain Max Length)",
       "target": "aliasSub(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_hash_chain_max'), '.*pools=([^;]*).*', 'Chain Max Length (\\1)')"
      }
     ]
    },
    {
     "title": "ZFS - ARC Memory Throttling",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_memory_throttle_count[$__rate_interval])",
       "legendFormat": "{{pools}}",
       "target": "aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=telegraf.zfs.arcstats_memory_throttle_count'), 'sum', 'pools')), 'pools')"
      }
     ]
    },
    {
     "title": "ZFS - L2ARC Size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "zfs_arcstats_l2_size{host=\"$hostname\"}",
       "legendFormat": "{{pools}}",
       "target": "aliasByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_l2_size'), 'pools')"
      }
     ]
    },
    {
     "title": "ZFS - L2ARC Hit %",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_l2_hits{host=\"$hostname\"}[$__rate_interval]) / (rate(zfs_arcstats_l2_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_l2_misses{host=\"$hostname\"}[$__rate_interval]))",
       "legendFormat": "{{pools}}",
       "target": "aliasSub(divideSeriesLists(aliasByTags(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_l2_hits')), 'pools'), aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_l2_(hits|misses)'), 'sum', 'pools')), 'pools')), \"divideSeries\\(([^,]*).*\", \"\\1\")"
      }
     ]
    },
    {
     "title": "ZFS - L2ARC Accesses / sec",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(zfs_arcstats_l2_hits{host=\"$hostname\"}[$__rate_interval]) + rate(zfs_arcstats_l2_misses{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "{{pools}}",
       "target": "aliasByTags(perSecond(groupByTags(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_l2_(hits|misses)'), 'sum', 'pools')), 'pools')"
      }
     ]
    },
    {
     "title": "ZFS - L2ARC Errors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"zfs_arcstats_l2_.*_error\", host=\"$hostname\"}, \"error\", \"$1\", \"__name__\", \"zfs_arcstats_l2_(.*)_error\")",
       "legendFormat": "{{pools}} ({{error}})",
       "target": "aliasSub(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.zfs.arcstats_l2_.*_error'), '.*_l2_([^_]*)_error;.*pools=([^;]*)', '\\1 - \\2')"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Throughput (B)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(net_bytes_recv{host=\"$hostname\", interface!=\"docker0\", interface!~\"veth.*\", interface!~\"br.*\"}[$__rate_interval])",
       "legendFormat": "{{interface}} - recv",
       "target": "aliasSub(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.net.bytes_', 'interface!=docker0', 'interface!=~veth*')), '.*bytes_([^;]*).*interface=([a-zA-Z0-9]*).*$', '\\2 (\\1)')"
      },
      {
       "expr": "rate(net_bytes_sent{host=\"$hostname\", interface!=\"docker0\", interface!~\"veth.*\", interface!~\"br.*\"}[$__rate_interval])",
       "legendFormat": "{{interface}} - sent",
       "target": "aliasSub(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.net.bytes_', 'interface!=docker0', 'interface!=~veth*')), '.*bytes_([^;]*).*interface=([a-zA-Z0-9]*).*$', '\\2 (\\1)')"
      }
     ]
    },
    {
     "title": "Network Throughput (Packets)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(net_packets_recv{host=\"$hostname\", interface!=\"docker0\", interface!~\"veth.*\", interface!~\"br.*\"}[$__rate_interval])",
       "legendFormat": "{{interface}} - recv",
       "target": "aliasSub(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.net.packets_*', 'interface!=docker0', 'interface!=~veth*')), '.*packets_([^;]*).*interface=([a-zA-Z0-9]*).*$', '\\2 (\\1)')"
      },
      {
       "expr": "rate(net_packets_sent{host=\"$hostname\", interface!=\"docker0\", interface!~\"veth.*\", interface!~\"br.*\"}[$__rate_interval])",
       "legendFormat": "{{interface}} - sent",
       "target": "aliasSub(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.net.packets_*', 'interface!=docker0', 'interface!=~veth*')), '.*packets_([^;]*).*interface=([a-zA-Z0-9]*).*$', '\\2 (\\1)')"
      }
     ]
    },
    {
     "title": "Network Errors/Drops/Retransmits/Discards",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate({__name__=~\"net_(err_in|err_out|drop|err|tcp_retranssegs|tcp_inerrs|udp_inerrors|udp_rcvbuferrors|udp_rcvbuferrors|udp_sndbuferrors|udp_incsumerrors|udplite_incsumerrors|udplite_inerrors|udplite_noports|udplite_rcvbuferrors|udplite_sndbuferrors|ip_inaddrerrors|ip_indiscards|ip_outdiscards|ip_outnoroutes|ip_reasmfails|ip_reasmtimeout|ip_inhdrerrors|ip_inunknownprotos|icmp_inerrors|icmp_outerrors|tcp_attemptfails|.*exceeded)\", host=\"$hostname\"}[$__rate_interval])) by (metric)",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "Internet Speed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      { "expr": "-internet_speed_download", "legendFormat": "down" },
      { "expr": "internet_speed_upload", "legendFormat": "up" }
     ]
    },
    {
     "title": "Internet Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "internet_speed_latency", "legendFormat": "down" }
     ]
    },
    {
     "title": "DNS Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "dns_query_query_time_ms", "legendFormat": "{{server}}" }
     ]
    },
    {
     "title": "IP Fragmentation",
     "type": "timeseries",
     "description": "Packets fragmented by system and count of fragments created as a result",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(net_ip_fragoks[$__rate_interval])",
       "legendFormat": "packets",
       "target": "aliasByNode(seriesByTag('host=~${hostname:regex}', 'name=telegraf.conntrack.ip_conntrack_count'), 2)"
      },
      {
       "expr": "rate(net_ip_fragcreates[$__rate_interval])",
       "legendFormat": "fragments"
      }
     ]
    },
    {
     "title": "Connections (Opens)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(net_tcp_activeopens{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "net_tcp_activeopens / sec",
       "target": "aliasByNode(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.net.tcp.*open')), 2)"
      },
      {
       "expr": "rate(net_tcp_passiveopens{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "net_tcp_passiveopens / sec",
       "target": "aliasByNode(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.net.tcp.*open')), 2)"
      },
      {
       "expr": "net_tcp_activeopens{host=\"$hostname\"}",
       "legendFormat": "net_tcp_activeopens"
      },
      {
       "expr": "net_tcp_passiveopens{host=\"$hostname\"}",
       "legendFormat": "net_tcp_passiveopens"
      }
     ]
    },
    {
     "title": "Connections (UDP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(netstat_udp_socket{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "netstat_udp_socket / sec",
       "target": "aliasByNode(perSecond(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.net.tcp.*open')), 2)"
      },
      {
       "expr": "netstat_udp_socket{host=\"$hostname\"}",
       "legendFormat": "netstat_udp_socket"
      }
     ]
    },
    {
     "title": "Connections (Tracked)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "conntrack_ip_conntrack_count{host=\"$hostname\"}",
       "legendFormat": "ip_conntrack_count",
       "target": "aliasByNode(seriesByTag('host=~${hostname:regex}', 'name=telegraf.conntrack.ip_conntrack_count'), 2)"
      }
     ]
    },
    {
     "title": "Connections (States)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"netstat.*\", __name__!=\"netstat_udp_socket\", host=\"$hostname\"}",
       "legendFormat": "{{__name__}}",
       "target": "aliasByNode(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.netstat.*'), 2)"
      }
     ]
    },
    {
     "title": "SYN Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(netstat_tcp_syn_recv{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "recv",
       "target": "aliasByNode(nonNegativeDerivative(seriesByTag('host=~${hostname:regex}', 'name=~telegraf.net.*exceeded')), 2)"
      },
      {
       "expr": "rate(netstat_tcp_syn_sent{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "ICMP Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(net_icmp_inmsgs{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(net_icmp_outmsgs{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "UDP Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(net_udp_indatagrams{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(net_udp_outdatagrams{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "TCP Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(net_tcp_insegs{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(net_tcp_outsegs{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "TCP Resets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(net_tcp_outrsts{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "net_tcp_outrsts"
      },
      {
       "expr": "rate(net_tcp_estabresets{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "net_tcp_estabresets"
      }
     ]
    },
    {
     "title": "IP Forwardings",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(net_ip_forwarding{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "TCP"
      },
      {
       "expr": "rate(net_ip_forwdatagrams{host=\"$hostname\"}[$__rate_interval])",
       "legendFormat": "UDP"
      }
     ]
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Docker CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "docker_container_cpu_usage_percent{host=\"$hostname\", cpu=\"cpu-total\"}",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Docker CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "increase(docker_container_cpu_throttling_throttled_periods{host=\"$hostname\", cpu=\"cpu-total\"}[$__rate_interval]) / increase(docker_container_cpu_throttling_periods{host=\"$hostname\", cpu=\"cpu-total\"}[$__rate_interval])",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Docker Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_mem_usage{host=\"$hostname\"}",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage / Process (>1%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "procstat_cpu_usage{host=\"$hostname\"} > 1",
       "legendFormat": "{{user}}/{{process_name}} ({{pid}})"
      }
     ]
    },
    {
     "title": "Memory Usage / Process (>10MB)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "procstat_memory_rss{host=\"$hostname\"} > 10000000",
       "legendFormat": "{{user}}/{{process_name}} ({{pid}})"
      }
     ]
    },
    {
     "title": "Disk Throughput / Processes (>100KB/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(procstat_write_bytes{host=\"$hostname\"}[$__rate_interval]) > 100000",
       "legendFormat": "{{user}}/{{process_name}} ({{pid}}) - write"
      },
      {
       "expr": "rate(procstat_read_bytes{host=\"$hostname\"}[$__rate_interval]) > 100000",
       "legendFormat": "{{user}}/{{process_name}} ({{pid}}) - read"
      }
     ]
    },
    {
     "title": "Disk IOps / Processes (>100)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(procstat_write_count{host=\"$hostname\"}[$__rate_interval]) > 100",
       "legendFormat": "{{user}}/{{process_name}} ({{pid}}) - writes"
      },
      {
       "expr": "rate(procstat_read_count{host=\"$hostname\"}[$__rate_interval]) > 100",
       "legendFormat": "{{user}}/{{process_name}} ({{pid}}) - reads"
      }
     ]
    },
    {
     "title": "File Descriptors / Processes (>100)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "procstat_num_fds{host=\"$hostname\"} > 100",
       "legendFormat": "{{user}}/{{process_name}} ({{pid}}"
      }
     ]
    },
    {
     "title": "Threads / Processes (>10)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "procstat_num_threads{host=\"$hostname\"} > 10",
       "legendFormat": "{{user}}/{{process_name}} ({{pid}})"
      }
     ]
    }
   ]
  }
 ]
}