global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/rules.yaml

scrape_configs:
  - job_name: telegraf
    static_configs:
      - targets: ['host.docker.internal:3004']
    metric_relabel_configs:
      # interrupts_CPU.+: Move CPU# from metric name to label
      - source_labels: [__name__]
        regex: 'interrupts_CPU(.+)'
        replacement: '$1'
        target_label: cpu
      - source_labels: [__name__]
        regex: 'interrupts_CPU(.+)'
        replacement: 'interrupts'
        target_label: __name__
      # soft_interrupts_CPU.+: Move CPU# from metric name to lael
      - source_labels: [__name__]
        regex: 'soft_interrupts_CPU(.+)'
        replacement: '$1'
        target_label: cpu
      - source_labels: [__name__]
        regex: 'soft_interrupts_CPU(.+)'
        replacement: 'soft_interrupts'
        target_label: __name__
      # net_.+: Duplicate metric name to enable rate(regex) instead of broken rate(label_replace(regexp))
      - source_labels: [__name__]
        regex: 'net_(.+)'
        replacement: 'net_$1'
        target_label: metric

remote_write:
  - url: http://localhost:3000/mimir/api/v1/push
    basic_auth:
      username: mimir
      password: mimir

